# Generated by Django 2.1.1 on 2018-09-10 13:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CityDict',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='城市名称')),
                ('add_time', models.DateTimeField(auto_now_add=True, verbose_name='添加时间')),
                ('desc', models.CharField(max_length=200, verbose_name='描述')),
            ],
            options={
                'verbose_name': '城市',
                'verbose_name_plural': '城市',
                'db_table': 'city_dict',
            },
        ),
        migrations.CreateModel(
            name='CourseOrganization',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='课程组织名字')),
                ('desc', models.TextField(verbose_name='组织描述')),
                ('click_num', models.IntegerField(verbose_name='点击次数')),
                ('fav_nums', models.IntegerField(verbose_name='收藏次数')),
                ('image', models.ImageField(default='images/org/default.jpg', upload_to='images/org/%Y/%m/%d')),
                ('address', models.CharField(max_length=150, verbose_name='地址')),
                ('add_time', models.DateTimeField(auto_now_add=True, verbose_name='添加时间')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='organizations', to='organization.CityDict')),
            ],
            options={
                'verbose_name': '课程组织信心',
                'verbose_name_plural': '课程组织信心',
                'db_table': 'course_organization',
            },
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='老师名字')),
                ('work_years', models.IntegerField(verbose_name='工作年限')),
                ('company', models.CharField(max_length=100, verbose_name='公司')),
                ('position', models.CharField(max_length=120, verbose_name='职位')),
                ('desc', models.CharField(max_length=300, verbose_name='教学特点')),
                ('click_nums', models.IntegerField(verbose_name='点击次数')),
                ('fav_nums', models.IntegerField(verbose_name='喜欢人数')),
                ('add_time', models.DateTimeField(auto_now_add=True, verbose_name='添加时间')),
                ('org', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teachers', to='organization.CourseOrganization', verbose_name='所属组织')),
            ],
            options={
                'verbose_name': '老师信息',
                'verbose_name_plural': '老师信息',
                'db_table': 'teacher',
            },
        ),
    ]
