# Generated by Django 2.1.1 on 2018-09-13 10:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='courseorganization',
            options={'verbose_name': '课程组织信息', 'verbose_name_plural': '课程组织信息'},
        ),
        migrations.AlterField(
            model_name='courseorganization',
            name='city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='organizations', to='organization.CityDict', verbose_name='所属城市'),
        ),
    ]
