# Generated by Django 2.1.1 on 2018-09-16 21:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0004_auto_20180916_2053'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrgType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('add_time', models.DateTimeField(auto_created=True)),
                ('name', models.CharField(max_length=20, verbose_name='机构类别')),
            ],
            options={
                'verbose_name': '机构类别',
                'verbose_name_plural': '机构类别',
                'db_table': 'org_type',
            },
        ),
        migrations.RemoveField(
            model_name='courseorganization',
            name='org_type',
        ),
        migrations.AddField(
            model_name='orgtype',
            name='org',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='org_type', to='organization.CourseOrganization'),
        ),
    ]
