# Generated by Django 2.1.1 on 2018-09-17 19:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0001_initial'),
        ('organization', '0005_auto_20180916_2154'),
    ]

    operations = [
        migrations.AddField(
            model_name='courseorganization',
            name='courses',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='org', to='course.Course'),
        ),
    ]
