# Generated by Django 2.1.1 on 2018-09-20 10:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0006_courseorganization_courses'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='orgtype',
            table='orgtype',
        ),
    ]
