# Generated by Django 2.1.1 on 2018-09-20 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0007_auto_20180920_1033'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orgtype',
            name='add_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
