# Generated by Django 2.1.1 on 2018-09-21 00:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0011_auto_20180920_2301'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orgtype',
            name='org',
        ),
        migrations.AlterField(
            model_name='courseorganization',
            name='OrgType',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='org', to='organization.OrgType', verbose_name='机构类别'),
        ),
        migrations.AlterField(
            model_name='courseorganization',
            name='city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='org', to='organization.CityDict', verbose_name='城市'),
        ),
    ]
