# Generated by Django 2.1.1 on 2018-09-21 00:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0012_auto_20180921_0006'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courseorganization',
            name='city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='city', to='organization.CityDict', verbose_name='城市'),
        ),
    ]
