# Generated by Django 2.1.1 on 2018-09-21 00:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0013_auto_20180921_0010'),
    ]

    operations = [
        migrations.RenameField(
            model_name='courseorganization',
            old_name='OrgType',
            new_name='orgtype',
        ),
    ]
