# Generated by Django 2.1.1 on 2018-09-23 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0014_auto_20180921_0011'),
    ]

    operations = [
        migrations.AddField(
            model_name='courseorganization',
            name='students',
            field=models.IntegerField(default=0, verbose_name='学生人数'),
        ),
        migrations.AlterField(
            model_name='courseorganization',
            name='courses',
            field=models.IntegerField(default=0, verbose_name='课程数'),
        ),
    ]
