# Generated by Django 2.1.1 on 2018-09-10 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='gender',
            field=models.CharField(choices=[('man', '男'), ('female', '女')], max_length=6, verbose_name='性别'),
        ),
    ]
