# Generated by Django 2.1.1 on 2018-09-13 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20180910_1433'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailverifyrecord',
            name='is_used',
            field=models.BooleanField(default=False),
        ),
    ]
